--- #YAML:1.0
name:               Locale-Maketext-Gettext
version:            1.28
abstract:           Joins gettext and Maketext frameworks
author:
    - imacat <imacat@mail.imacat.idv.tw>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
